#spring.application.name=ems-backend
#
#spring.datasource.url=jdbc:mysql://localhost:3306/employee
#spring.datasource.username=root
#spring.datasource.password=Saad@123
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL8Dialect
#spring.mvc.pathmatch.matching-strategy=ant-path-matcher
#
##server.port=8082


# =========================
# SERVER (optional for Render)
# =========================
server.port=8080

# =========================
# POSTGRESQL (RENDER DB)
# =========================
spring.datasource.url=jdbc:postgresql://dpg-d7rjld28qa3s73diad3g-a.oregon-postgres.render.com/ems_db_qkjd?sslmode=require
spring.datasource.username=ems_db_qkjd_user
spring.datasource.password=XCJCxwKLOEXSsQKfUGv83TEoMfHULXPq
spring.datasource.driver-class-name=org.postgresql.Driver

# =========================
# JPA / HIBERNATE
# =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# =========================
# CORS (if needed globally)
# =========================
spring.web.cors.allowed-origins=*
spring.web.cors.allowed-methods=*

# =========================
# JWT (if you use secret here)
# =========================
# jwt.secret=your-secret-key